name: Common Checks

on:
  workflow_call:
    inputs:
      run_pr_title_check:
        required: true
        type: boolean
      run_pr_email_check:
        required: true
        type: boolean
      run_signed_off_check:
        required: true
        type: boolean
jobs:
  common-checks-on-pr:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
         repository: ravalinamburi/common_scripts
         path: common_scripts

    - name: Write environment variables to a file
      run: |
        echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_WORKSPACE/env.list
        echo "PR_EMAIL=${{ github.event.pull_request.user.email }}" >> $GITHUB_WORKSPACE/env.list
        cat $GITHUB_WORKSPACE/env.list
        # Add more environment variables as needed

    - name: Make scripts executable
      run: | 
        chmod +x ${{ github.workspace }}/common_scripts/scripts/*.sh

    - name: Pull Docker image
      run: |
        docker pull ubuntu:latest

    - name: Run Docker container
      run: |
        docker run --name my-github-runner -d -v ${{ github.workspace }}/common_scripts/scripts:/usr/local/bin/scripts -v ${{ github.workspace }}/env.list:/env.list ubuntu:latest tail -f /dev/null
    - name: PR Title Check
      if: ${{ inputs.run_pr_title_check }}
      run: |
        docker exec my-github-runner /bin/bash -c "source /env.list && /usr/local/bin/scripts/pr-title-check.sh"

    - name: PR Email Check
      if: ${{ inputs.run_pr_email_check }}
      run: |
        docker exec my-github-runner /bin/bash -c "source /env.list && /usr/local/bin/scripts//pr-email-check.sh"

    - name: Signed-Off Check
      if: ${{ inputs.run_signed_off_check }}
      run: |
        docker exec my-github-runner /bin/bash -c "source /env.list && /usr/local/bin/scripts/signed-off-check.sh"

    # Ensure cleanup steps always run, regardless of success/failure of previous steps
    - name: Cleanup Docker container
      if: always()
      run: |
        docker stop my-github-runner
        docker rm my-github-runner

    - name: Remove cloned repository
      if: always()
      run: |
        rm -rf ${{ github.workspace }}/common_scripts
    
