name: Common Checks

on:
  workflow_call:
    inputs:
      run_pr_title_check:
        required: true
        type: boolean
      run_pr_email_check:
        required: true
        type: boolean
      run_signed_off_check:
        required: true
        type: boolean
jobs:
  common-checks-on-pr:
    runs-on: [self-hosted, x64, Linux]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
         repository: ravalinamburi/common_scripts
         path: common_scripts

    - name: Pull Docker image
      run: |
        docker pull ubuntu:latest

    - name: Run Docker container
      run: |
        docker run --name my-github-runner -d -v ${{ github.workspace }}/common_scripts/scripts:/usr/local/bin/scripts ubuntu:latest tail -f /dev/null

    - name: PR Title Check
      if: ${{ inputs.run_pr_title_check }}
      run: |
        docker exec my-github-runner /usr/local/bin/scripts/pr-title-check.sh

    - name: PR Email Check
      if: ${{ inputs.run_pr_email_check }}
      run: |
        docker exec my-github-runner /usr/local/bin/scripts/pr-email-check.sh

    - name: Signed-Off Check
      if: ${{ inputs.run_signed_off_check }}
      run: |
        docker exec my-github-runner /usr/local/bin/scripts/signed-off-check.sh

    - name: Cleanup
      run: |
        docker stop my-github-runner
        docker rm my-github-runner
