name: Test Docker Login

on:
  workflow_dispatch:

jobs:
  test-docker-login:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to private Docker registry
      uses: docker/login-action@v2
      with:
        registry: docker-registry.qualcomm.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
